<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'templado\\debug\\call' => '/Call.php',
                'templado\\debug\\coverageprinter' => '/CoveragePrinter.php',
                'templado\\debug\\textprinter' => '/TextPrinter.php',
                'templado\\debug\\tracelog' => '/TraceLog.php',
                'templado\\debug\\tracer' => '/Tracer.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
